name: Docker Hub Push

on:
  push:
    branches:
      - 'master'
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: varbrad/go-server:latest
