name: Reusable workflow example

on:
  workflow_call:
    inputs:
      context:
        required: false
        type: string
        default: .
      tag:
        required: true
        type: string
    secrets:
      username:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}
      - name: Build & Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ input.context }}
          push: true
          tags: ${{ input.tag }}
          cache-from: type=registry,ref=${{ input.tag }}
          cache-to: type=inline  